# Dependencies
markdown:         kramdown
highlighter:         rouge

# Permalinks
permalink:        /:categories/:year/:month/:day/:title.html

# Setup
name:            "Ryan Yang"
tagline:          ''
description:      'Everything about Ryan Yang J.L.'
url:              
static_url:       'http://static-fc3v5i52q0hd93op6.s3-website-ap-southeast-1.amazonaws.com'
exclude:          ['nbproject']

author:
  name:           Ryan Yang
  email:          ryan.yjl@gmail.com
  url:            http://ryan-yjl.com

gems:             [jekyll-paginate,jekyll-sitemap]

paginate:         3

#jekyll-archives:
#  enabled: 'all'
#  layout: 'category'

# Custom vars
version:          2.0.0

social:
  tumblr:           http://ryan-yjl.tumblr.com/
  github:           https://github.com/Ryan-YJL
  twitter: 			https://twitter.com/RyanYJL
  email:			ryan.yjl@gmail.com
  

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
